In [2]:
#@title
#package for social network scraping
!pip install -q snscrape transformers matplotlib wordcloud

In [4]:
pip install tweepy

Collecting tweepy
  Downloading tweepy-4.13.0-py3-none-any.whl (102 kB)
     ---------------------------------------- 0.0/102.8 kB ? eta -:--:--
     ---------------------------------------- 102.8/102.8 kB ? eta 0:00:00
Requirement already satisfied: requests<3,>=2.27.0 in c:\users\temit\anaconda3\envs\myenv\lib\site-packages (from tweepy) (2.28.1)
Collecting oauthlib<4,>=3.2.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ---------------------------------------- 0.0/151.7 kB ? eta -:--:--
     -------------------------------------- 151.7/151.7 kB 9.4 MB/s eta 0:00:00
Collecting requests-oauthlib<2,>=1.2.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\temit\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.27.0->tweepy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\temit\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.27.0->tweepy) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\temit\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\temit\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2022.12.7)
Installing collected packages: oauthlib, requests-oauthlib, tweepy
Successfully installed oauthlib-3.2.2 requests-oauthlib-1.3.1 tweepy-4.13.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
#@title
# Import libraries
import pandas as pd
import tweepy
import warnings
warnings.filterwarnings('ignore')
import snscrape.modules.twitter as sntwitter
import requests

In [7]:
# Query by Advanced text search
Topic = input('Search Criteria (Use OR where multiple words can be used):')
Location = input('Location:')
StDate = input('Start Date (YYYY-MM-DD):')
EnDate = input('End Date (YYYY-MM-DD):')
maxTweets = int(input('Maximum No of Tweets:'))

# Creating list to append tweet data to
tweets_list = []

query = '('+Topic+')'+' near:"'+ Location + '" lang:en until:'+EnDate+ ' since:'+StDate + ' -filter:links -filter:retweet'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
    if i>maxTweets:
        break
    tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.retweetCount, tweet.viewCount])

# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Retweet', 'Views'])

#tweets_df['Datetime'] = tweets_df['Datetime'].dt.tz_localize(None)

# Display first 5 entries from dataframe
tweets_df

Search Criteria (Use OR where multiple words can be used): Strike
Location: London
Start Date (YYYY-MM-DD): 2023-01-01
End Date (YYYY-MM-DD): 2023-03-05
Maximum No of Tweets: 100

,Datetime,Tweet Id,Text,Username,Retweet,Views
0,2023-03-04 22:22:38+00:00,1632144546829139968,Is a strike on #Iran on the horizon? ‚ò¢Ô∏èüöÄ,EihabNakib,0,62
1,2023-03-04 19:53:43+00:00,1632107071628877825,@Bill4Brexit Thats almost as much as a Pimlico...,alan_ridgley,0,33
2,2023-03-04 19:33:28+00:00,1632101976245673984,@Phoenix4517 @JMagosh @ja_hodges69 The pension...,colinelves,0,41
3,2023-03-04 19:30:46+00:00,1632101294306459649,@Phoenix4517 @JMagosh @ja_hodges69 Actually we...,colinelves,0,28
4,2023-03-04 17:10:41+00:00,1632066041705791489,Nelson take a bow! What a strike ü§ùüèΩ,yian_arest,0,65
...,...,...,...,...,...,...
96,2023-02-23 21:22:40+00:00,1628867965994119171,Minding my brothers dog for the week which has...,fkaollie,0,3547
97,2023-02-23 15:23:35+00:00,1628777600062566401,@tom_lennylad What a sensational strike partne...,pauljam19759849,0,59
98,2023-02-23 14:29:58+00:00,1628764104046309378,"Neighbours, people of London please be careful...",kyasatn,0,60
99,2023-02-23 13:27:11+00:00,1628748305910956032,@ChisCommons @VisitChis @ChisMatters @Chislehu...,MikeJackBR7,0,50
100,2023-02-23 12:27:57+00:00,1628733399941750787,@TaffLondonWelsh I do live in london now my lo...,everett_michele,0,13